version: '3.8'

services:
  minimal-cors-server:
    build:
#      context: https://github.com/MatthiasHarzer/ascii-video-server.git
      dockerfile: Dockerfile
    ports:
      - "9997:8000"
    environment:
      - ALWAYS_LOADED_FILES=
      - API_KYE=
      - MAX_PARALLEL_RUNS=5
    volumes:
      - ./files:/app/files
    restart: always
